import Link from "next/link";

import styles from "../legal.module.css";

export default function TermsPage() {
  return (
    <main className={styles.page}>
      <article className={styles.container}>
        <Link href="/" className={styles.back}>
          ← Back to home
        </Link>
        <h1>Terms of Service</h1>
        <p className={styles.updated}>Last updated: July 2026</p>

        <p>
          These Terms of Service (&quot;Terms&quot;) govern your access to and use of
          FinDataShield (&quot;FinDataShield&quot;, &quot;we&quot;, &quot;us&quot;, or
          &quot;our&quot;), including our website, application programming interfaces,
          and related services (collectively, the &quot;Service&quot;). By creating an
          account or using the Service, you agree to these Terms.
        </p>

        <h2>1. The Service</h2>
        <p>
          FinDataShield provides a software-as-a-service platform for generating
          synthetic financial datasets and associated compliance documentation. The
          Service is intended for machine learning development, testing, sandboxing,
          and related lawful business purposes.
        </p>

        <h2>2. Data Ownership</h2>
        <p>
          You retain all right, title, and interest in and to the datasets, exports,
          and compliance reports you generate through the Service (&quot;Generated
          Data&quot;), subject to these Terms and applicable law. FinDataShield does
          not claim ownership of your Generated Data. We store Generated Data on your
          behalf solely to provide the Service, including saving datasets to your
          account history and enabling re-download.
        </p>

        <h2>3. Synthetic Data Disclaimer</h2>
        <p>
          All data produced by FinDataShield is synthetic and is generated by
          artificial intelligence. Generated Data is not derived from real customer
          records and must not be represented as real production or customer data.
        </p>
        <p>
          EU AI Act compliance reports and similar outputs are provided for
          informational and documentation purposes only. They do not constitute legal
          advice, regulatory certification, audit approval, or a guarantee that your
          use of Generated Data will satisfy any regulatory, compliance, or
          supervisory requirement in any jurisdiction. You are solely responsible for
          evaluating whether Generated Data and any compliance documentation are
          suitable for your intended use.
        </p>

        <h2>4. Accounts and Acceptable Use</h2>
        <p>You agree to:</p>
        <ul>
          <li>Provide accurate account information and keep your credentials secure.</li>
          <li>Use the Service only for lawful purposes.</li>
          <li>
            Not attempt to bypass usage limits, access controls, or security measures.
          </li>
          <li>
            Not use the Service to generate content intended to deceive regulators,
            customers, or third parties about the origin of data.
          </li>
        </ul>

        <h2>5. Subscriptions, Payment, and Cancellation</h2>
        <p>
          Paid plans are billed in USD on a monthly or yearly basis as selected at
          checkout. By subscribing, you authorize us and our payment processor (Stripe)
          to charge your selected payment method on a recurring basis until you
          cancel.
        </p>
        <p>
          Subscription fees are non-refundable except where required by applicable law.
          You may cancel at any time through your billing portal or by contacting us;
          cancellation takes effect at the end of the current billing period. Downgrading
          or canceling does not entitle you to a refund for fees already paid.
        </p>
        <p>
          We may change pricing or plan features with reasonable notice. Continued use
          after a price change constitutes acceptance of the updated pricing for
          subsequent billing periods.
        </p>

        <h2>6. Usage Limits</h2>
        <p>
          Each plan includes a monthly example generation limit. Usage resets at the
          start of each calendar month unless otherwise stated. We enforce limits
          server-side to ensure fair use of the platform.
        </p>

        <h2>7. Intellectual Property</h2>
        <p>
          FinDataShield and its licensors retain all rights in the Service, including
          software, branding, documentation, and underlying technology. These Terms
          do not grant you any rights to our intellectual property except the limited
          right to use the Service as described herein.
        </p>

        <h2>8. Limitation of Liability</h2>
        <p>
          To the maximum extent permitted by law, FinDataShield and its directors,
          officers, employees, and affiliates shall not be liable for any indirect,
          incidental, special, consequential, or punitive damages, or any loss of
          profits, revenue, data, or business opportunities, arising from your use of
          the Service or Generated Data.
        </p>
        <p>
          Our total aggregate liability for any claim arising out of or relating to
          the Service shall not exceed the greater of (a) the amount you paid to
          FinDataShield in the twelve (12) months preceding the claim, or (b) one
          hundred US dollars (USD $100).
        </p>
        <p>
          Nothing in these Terms excludes or limits liability that cannot be excluded
          or limited under applicable law, including liability for fraud or under
          applicable consumer protection legislation.
        </p>

        <h2>9. Disclaimer of Warranties</h2>
        <p>
          The Service is provided on an &quot;as is&quot; and &quot;as available&quot;
          basis. We do not warrant that the Service will be uninterrupted, error-free,
          or that Generated Data will meet your specific requirements or regulatory
          expectations.
        </p>

        <h2>10. Governing Law</h2>
        <p>
          These Terms are governed by the laws of Western Australia, Australia, without
          regard to conflict-of-law principles. You agree that the courts of Western
          Australia shall have exclusive jurisdiction to resolve any dispute arising
          from these Terms or the Service, subject to any non-excludable rights you
          may have under applicable consumer law.
        </p>

        <h2>11. Changes to These Terms</h2>
        <p>
          We may update these Terms from time to time. Material changes will be
          posted on this page with an updated date. Your continued use of the Service
          after changes take effect constitutes acceptance of the revised Terms.
        </p>

        <h2>12. Contact</h2>
        <p>
          Questions about these Terms may be sent to{" "}
          <a href="mailto:viktorm@findatashield.com">viktorm@findatashield.com</a>.
        </p>
      </article>
    </main>
  );
}
