import { jsPDF } from "jspdf";

export type ComplianceReport = {
  report_id: string;
  generated_at: string;
  dataset_type: string;
  total_examples: number;
  quality_score: string;
  synthetic_confirmed: boolean;
  pii_confirmed_absent: boolean;
  intended_use: string;
  risk_classification: string;
  regulation_compliance: string;
  data_standards: string;
  audit_trail: string;
  recommendations: string[];
};

const MARGIN = 20;
const LABEL_COL_WIDTH = 58;
const HEADER_HEIGHT = 42;

function addPageIfNeeded(doc: jsPDF, y: number, required = 20): number {
  const pageHeight = doc.internal.pageSize.getHeight();
  if (y + required > pageHeight - MARGIN) {
    doc.addPage();
    return MARGIN;
  }
  return y;
}

function drawHeader(doc: jsPDF) {
  const pageWidth = doc.internal.pageSize.getWidth();

  doc.setFillColor(7, 19, 37);
  doc.rect(0, 0, pageWidth, HEADER_HEIGHT, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("FinDataShield", MARGIN, 18);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(193, 211, 239);
  doc.text("Synthetic Financial Data & EU AI Act Compliance", MARGIN, 27);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(255, 255, 255);
  doc.text("EU AI Act Compliance Report", MARGIN, 36);

  doc.setFillColor(16, 138, 79);
  doc.roundedRect(pageWidth - MARGIN - 38, 14, 38, 10, 2, 2, "F");
  doc.setFontSize(8);
  doc.setTextColor(255, 255, 255);
  doc.text("COMPLIANT", pageWidth - MARGIN - 34, 20.5);
}

function drawTableRow(
  doc: jsPDF,
  y: number,
  label: string,
  value: string,
  shaded: boolean,
): number {
  const pageWidth = doc.internal.pageSize.getWidth();
  const contentWidth = pageWidth - MARGIN * 2;
  const valueWidth = contentWidth - LABEL_COL_WIDTH - 6;

  const valueLines = doc.splitTextToSize(value, valueWidth);
  const rowHeight = Math.max(12, valueLines.length * 5 + 7);

  y = addPageIfNeeded(doc, y, rowHeight + 2);

  if (shaded) {
    doc.setFillColor(248, 251, 255);
    doc.rect(MARGIN, y - 4, contentWidth, rowHeight, "F");
  }

  doc.setDrawColor(227, 234, 245);
  doc.setLineWidth(0.2);
  doc.line(MARGIN, y - 4 + rowHeight, MARGIN + contentWidth, y - 4 + rowHeight);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(74, 100, 134);
  doc.text(label, MARGIN + 3, y + 3);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(23, 52, 89);
  doc.text(valueLines, MARGIN + LABEL_COL_WIDTH + 3, y + 3);

  return y + rowHeight;
}

export function downloadComplianceReportPdf(report: ComplianceReport) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();

  drawHeader(doc);

  let y = HEADER_HEIGHT + 14;

  doc.setTextColor(15, 39, 72);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("Report Details", MARGIN, y);
  y += 10;

  const rows: [string, string][] = [
    ["Report ID", report.report_id],
    ["Generated At", report.generated_at],
    ["Dataset Type", report.dataset_type],
    ["Total Examples", String(report.total_examples)],
    ["Quality Score", report.quality_score],
    ["Synthetic Confirmed", report.synthetic_confirmed ? "true" : "false"],
    ["PII Confirmed Absent", report.pii_confirmed_absent ? "true" : "false"],
    ["Intended Use", report.intended_use],
    ["Risk Classification", report.risk_classification],
    ["Regulation Compliance", report.regulation_compliance],
    ["Data Standards", report.data_standards],
    ["Audit Trail", report.audit_trail],
  ];

  rows.forEach(([label, value], index) => {
    y = drawTableRow(doc, y, label, value, index % 2 === 0);
  });

  y = addPageIfNeeded(doc, y, 30);
  y += 8;

  doc.setFillColor(20, 43, 77);
  doc.rect(MARGIN, y - 6, pageWidth - MARGIN * 2, 10, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Recommendations", MARGIN + 3, y);
  y += 12;

  report.recommendations.forEach((recommendation, index) => {
    y = addPageIfNeeded(doc, y, 18);
    const bulletLines = doc.splitTextToSize(
      `${index + 1}. ${recommendation}`,
      pageWidth - MARGIN * 2 - 4,
    );

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(40, 70, 101);
    doc.text(bulletLines, MARGIN + 2, y);
    y += bulletLines.length * 5 + 6;
  });

  y = addPageIfNeeded(doc, y, 12);
  doc.setFont("helvetica", "italic");
  doc.setFontSize(8);
  doc.setTextColor(119, 121, 134);
  doc.text(
    "Generated by FinDataShield — This report documents synthetic dataset compliance under the EU AI Act.",
    MARGIN,
    doc.internal.pageSize.getHeight() - 12,
  );

  const safeId = report.report_id.replaceAll(/[^\w-]/g, "-").slice(0, 40);
  doc.save(`compliance-report-${safeId}.pdf`);
}
